import Head from "next/head";
import styled from "styled-components";
export const Tester = styled.div`
  width: 500px;
  height: 500px;
  background-color: bisque;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Portifólio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Tester>oi</Tester>
    </>
  );
}
